### ISSUE TITLE
Does not restore default frame cursor

### ISSUE THREAD

**Issue by wavexx** [duckwork/electric-cursor#1]
I have the following config:

````
(setq electric-cursor-default-cursor t
      electric-cursor-alist '((overwrite-mode . bar)))
(electric-cursor-mode 1)
````

Heretic, I know ;). However, with the latest changes, toggling electric-cursor-mode sets the cursor to bar instead of leaving it to the frame default (box), whereas it used to work correctly a week ago?

**Comment by duckwork** [comment]
Hm, I can't replicate this issue, but it's because using an `emacs -q` instance, `electric-cursor` doesn't do *anything*! I'll look into this and try to publish a v0.2 today.

**Comment by duckwork** [comment]
@wavexx I've updated `electric-cursor` to v0.2, which should fix your issue in addition to just being generally better :) Thanks for the issue report!

**Comment by wavexx** [comment]
Thank for writing electric-cursor. It's small, but super-neat compared to read the mode-line =)
